name: Test

permissions:
  contents: write

on: [push]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      matrix:
        os: [
            ubuntu-24.04,
            windows-latest,
            macos-latest,
            macos-13,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo run
        run: |
          if [ ! -f ~/.bashrc ]; then
              touch ~/.bashrc
          fi
          cargo run
          cargo run -- get
      - name: add path
        run: |
          cargo run -- add /a/b/c
          cargo run -- add c:/b/c
      - name: has path
        run: |
          source ~/.bashrc
          cargo run -- has /a/b/c
          cargo run -- has "c:/b/c"
          cargo run -- has "C:\Windows"
          cargo run -- has /bin
          cargo run -- has /usr/bin
      - name: github path
        run: |
          cargo run -- is_github
          cargo run -- add_github_path /x/y
          cargo run -- add_github_path c:/x/y
      - name: test github path
        run: |
          cargo run -- has /x/y
          cargo run -- has c:/x/y
